name: 'phillipadsmith.com re-loaded for 2014'
# Also used in the RSS plugin
url: 'http://www.phillipadsmith.com' 
description: "Veteran digital publishing consultant, online advocacy specialist, and strategic convener." 
author: 'Phillip Smith' 
copyright: 'Copyleft 2014' 
tagline: "Pushing bits since '96"
mode: 'development'
markdown: 'kramdown'
pygments: true
# excerpt_separator: "\n\n" TODO Fix excepts on old posts
permalink: /:year/:month/:title.html
exclude: 
    - 'ui/less'
    - '**.less'
    - 'node_modules'
    - 'package.json'
    - 'Gruntfile.js'
    - 'bower.json'
    - '*.cs'
    - 'Gemfile*'
    - 'IDEAS.md'
tag_archive:
    layout: archive_tag
    path: /tag/ 
category_archive:
    layout: archive_category
fbadmins:
    - 511961152
img_lrg: '/ui/img/phillipadsmith-500x500.jpg'
