name: 'phillipadsmith.com re-loaded for 2014'
# Also used in the RSS plugin
url: 'http://www.phillipadsmith.com' 
description: "Pushing bits since '96" 
author: 'Phillip Smith' 
copyright: 'Copyleft 2014' 
#rss_path       - (optional) the path to the feed (if not specified "/" will be used)
# rss_name       - (optional) the name of the rss file (if not specified "rss.xml" will be used)
#rss_post_limit - (optional) the number of posts in the feed
tagline: "Pushing bits since '96"
mode: 'development'
markdown: 'kramdown'
pygments: true
# excerpt_separator: "\n\n" TODO Fix excepts on old posts
permalink: /:year/:month/:title.html
exclude: 
    - 'ui/less'
    - '**.less'
    - 'node_modules'
    - 'package.json'
    - 'Gruntfile.js'
    - 'bower.json'
    - '*.cs'
    - 'Gemfile*'
    - 'IDEAS.md'
tag_archive:
    layout: archive_tag
    path: /tag/ 
category_archive:
    layout: archive_category
fbadmins:
    - 511961152
